### ISSUE TITLE
/kill RESTful API does not work

### ISSUE THREAD

**Issue by AndroidDesigner** [bifromqio/bifromq#103]
Hello

BifroMQ version: 3.3.2

I have an active subscriber:
```
 mosquitto_sub -h localhost -p 1883 -i test1 -u test1 -P 123456 -t "test"
```

Now I call the ``/kill`` API:
```
//kill all:
curl -X DELETE http://localhost:8091/kill -H "tenant_id:DevOnly" -H "client_type: MQTT"

//kill specific client:
curl -X DELETE http://localhost:8091/kill -H "tenant_id:DevOnly" -H "client_type: MQTT" -H "user_id: test1" -H "client_id: test1"
```
it returns 200, but nothing happens and my subscriber is connected yet.

**Comment by popduke** [comment]
`mosquitto_sub` reconnects automatically. You can enable its debug output with the `-d` option and check out what’s going on underneath, or use other client tools for verification.

**Comment by AndroidDesigner** [comment]
You're absolutely right!
