### ISSUE TITLE
Support for MQTT 5

### ISSUE THREAD

**Issue by markrey** [bifromqio/bifromq#21]
Great work in opensousing a capable MQTT broker. 
Any plans to launch MQTT 5 support?

Thanks

**Comment by popduke** [comment]
We do have plans to support MQTT5, but there is no exact timeline yet. It is expected to be initiated by the end of this year or early next year

**Comment by markrey** [comment]
Thank you.
Any plans for cluster / Web ui / API releases?
It's a great product but lots of things are unknown.

**Comment by popduke** [comment]
@markrey 
We just release [v2.0.0](https://github.com/baidu/bifromq/releases/tag/v2.0.0) which includes cluster and API support. 
As for WebUI, We currently do not intend to include the feature as part of the BifroMQ project. Here are some [thoughts](https://bifromq.io/docs/2.0.0/faq/bifromq/#why-doesnt-bifromq-have-a-management-consoleui-interface) on this matter.

**Comment by popduke** [comment]
MQTT5 has been fully supported in [3.0](https://github.com/bifromqio/bifromq/releases/tag/v3.0.0) release
