### ISSUE TITLE
BifroMQ 不支持规则引擎吗?

### ISSUE THREAD

**Issue by objectboy2016** [bifromqio/bifromq#52]
百度BifroMQ 团队你们好, 看了下官方关于BifroMQ 的文档, 里面没有关于任何规则引擎的介绍, 请问BifroMQ 是不是不支持规则引擎呢? 谢谢

**Comment by popduke** [comment]
规则引擎不会直接包含在BifroMQ里，这里有说明：https://bifromq.io/docs/faq/bifromq/#does-bifromq-include-a-built-in-rule-engine
