### ISSUE TITLE
Connections be kicked when shuting down one BifroMQ node

### ISSUE THREAD

**Issue by mafei6827** [bifromqio/bifromq#54]
**Describe the bug**
In cluster mode, shutting down a BifroMQ node may result in the possibility of MQTT connections on other nodes being kicked off.

**Logs**
event log： KICKED

**BifroMQ**
- Version: v2.1

**Comment by mefly2012** [comment]
你配置了高可用吗？
dist_worker_range_voter_count    3    至少为3，最好奇数值
inbox_store_range_voter_count    1    至少为3，最好奇数值
retain_store_range_voter_count    3    至少为3，最好奇数值
我配置了这个看起来就不出现这个问题了。

**Comment by mafei6827** [comment]
> 你配置了高可用吗？ dist_worker_range_voter_count 3 至少为3，最好奇数值 inbox_store_range_voter_count 1 至少为3，最好奇数值 retain_store_range_voter_count 3 至少为3，最好奇数值 我配置了这个看起来就不出现这个问题了。

目前定位下来跟voter_count不相关，在此场景下是概率性出现的，修复已提交在v2.1.1。
