### ISSUE TITLE
bifromq 管理控制台有没有规划,可以实现监控,配置等功能

### ISSUE THREAD

**Issue by ccwxl** [bifromqio/bifromq#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by popduke** [comment]
这个问题在官网FAQ里有[回答](https://bifromq.io/zh-Hans/docs/faq/bifromq/#bifromq-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E7%AE%A1%E7%90%86%E6%8E%A7%E5%88%B6%E5%8F%B0-ui-%E7%95%8C%E9%9D%A2)。
