### ISSUE TITLE
单Pub单Sub 单Topic情况下的无法保障topic顺序消费

### ISSUE THREAD

**Issue by dddddkkkkk** [bifromqio/bifromq#61]
**Describe the bug**
在使用jmete进行压测时发现。使用jmeter一个线程qos0(body中存在顺序递增seq)，向一个topic中发送消息，Sub也是唯一订阅者消费。在观察sub端打印日志时发现，打印出的seq并不是顺序递增的，而是会出现乱序的情况。

*** Pub Client ***
Jmeter 配置
![image](https://github.com/bifromqio/bifromq/assets/39723179/872ce649-c9c2-4a17-b19b-1ed97c79e9aa)
![image](https://github.com/bifromqio/bifromq/assets/39723179/6e5789ac-6a59-4aaf-9327-d9e388f93e84)
![image](https://github.com/bifromqio/bifromq/assets/39723179/4464a276-de18-4506-b5ec-60943eed24ce)
![image](https://github.com/bifromqio/bifromq/assets/39723179/da374592-29a7-42dd-b6da-4874815589d7)
![image](https://github.com/bifromqio/bifromq/assets/39723179/404aebc7-c126-4694-b8e1-12e0c97c04d0)

*** SUB Client ***
- centos 7
- CPU: 4
- Memory: 4G
采用java 进行接收
```
       <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>
```
- MQTT Connection:
   - Clean Session:  false
   - ClientIdentifier: 
   - etc...
- MQTT Sub:
   - TopicFilter:  mqtt_test_local_1
   - QoS: 0

**Logs**
出现如图所示 seq乱序情况
![image](https://github.com/bifromqio/bifromq/assets/39723179/803c263a-5d5b-442a-8193-8c88e1b8b143)

** biformq 集群**
集群采用k8s部署，4核10g *3 

**JVM:**
- Version: 17

**BifroMQ**
- Version: 2.1.0
- Non-Default Configuration: 
- bifromq-start.sh   -server -DMsgPubPerSec=100000 -DInBoundBandWidth=1073741824 -DOutBoundBandWidth=1073741824 
- standalone.yml
```
#edit
mqttServerConfig:
  tcpListener:
    port: 1883
  maxMsgByteSize: 1048576
  maxConnBandwidth: 1073741824
  maxConnPerSec: 5000
```

后序发现在windows搭建本地bifromq 单机版也能复现该问题。

**Comment by mafei6827** [comment]
问题确认，已修复发版[v2.1.2](https://github.com/bifromqio/bifromq/releases/tag/v2.1.2)
