### ISSUE TITLE
authPlugin无法进入auth(MQTT5AuthData authData) 方法

### ISSUE THREAD

**Issue by dddddkkkkk** [bifromqio/bifromq#65]
在开发bifrom auth 插件时发现，重写IAuthProvider 下auth(MQTT5AuthData authData)方法后，mqtt5 auth方法在建立连接时并未生效。而是会一直走auth(MQTT3AuthData mqtt3AuthData) 方法。
bifromq version:3.0.0-beta.1

![image](https://github.com/bifromqio/bifromq/assets/39723179/0956789d-0593-446a-be3f-418bb083b0ea)
![image](https://github.com/bifromqio/bifromq/assets/39723179/f3941314-64f9-4430-b2ea-d4193434120e)
![image](https://github.com/bifromqio/bifromq/assets/39723179/9ad453bd-204a-40fd-97a4-fd0b75ab9f4b)

![image](https://github.com/bifromqio/bifromq/assets/39723179/3b769bc9-ea5b-4a28-9d1d-37e0a8b01ad2)

**Comment by objectboy2016** [comment]
已经解决了吗    能加个QQ指教下?  谢谢
