### ISSUE TITLE
bifromq 性能测试系统可能阻塞在DistWorkerCoProcFactory的 ForkJoinPool 

### ISSUE THREAD

**Issue by masterOcean** [bifromqio/bifromq#81]
**bifromq 性能测试可能阻塞点**
3台节点组成 bifromq 集群，连接了 4w client，每个 client 发送 4k 的 body， 集群的 direct memory 很快就满了然后集群就宕机了。我们抓了正常压测下的集群 bootstrap 节点的 off-cpu 火焰图（arthas 抓取 event type 为 lock 的火焰图），发现可能的阻塞点可能在DistWorkerCoProcFactory的 ForkJoinPool ，98%的时间是在 ForkJoinPool 上。
![image](https://github.com/bifromqio/bifromq/assets/43053697/f2f704aa-42fc-41e3-9dd6-065d01389900)
Netty 网络收发只占了 2% 时间不到

**BifroMQ**
- Version: 2.1.1

**Comment by popduke** [comment]
1. lock event sampling并不能说明是阻塞，caffeine cache默认用FJP执行cache cleanup task，BifroMQ多处使用了cache，对锁的使用占了sample的大部分很正常。
2. 压测环境是什么？cpu，内存，网卡，bifromq的启动参数, etc
3. 压测参数是什么？频率，qos，cleansession，topic，topic filter，etc
