### ISSUE TITLE
建议在POM文件中升级lombok版本以便支持Java21的编译

### ISSUE THREAD

**Issue by haroldyong** [bifromqio/bifromq#86]
使用JDK21编译 bifromq (tag v3.0.2) 会出现“NoSuchFieldError 'com.sun.tools.javac.tree.JCTree qualid' ” 错误。

解决方案：
1、在 bifromq-parent 的pom.xml 中升级 => <lombok.version>1.18.30</lombok.version>
2、在base-hookloader和base-env-provider中的pom.xml 中添加 

     <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

**Comment by popduke** [comment]
Thanks for the feedback, the issue should be [resolved](https://github.com/bifromqio/bifromq/commit/2c92cce14d878909ba71f6d6e6c9cacf34a6613f#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R106) , have a try.
