### ISSUE TITLE
Bifromq Bridge

### ISSUE THREAD

**Issue by Wlh0** [bifromqio/bifromq#89]
Bifromq文档上说支持扩展桥接功能，但是没有具体的使用手册，所以可以通过配置文件实现桥接功能吗？

**Comment by popduke** [comment]
桥接功能相对通用，适合作为独立项目，目前没有内置在bifromq里

**Comment by linjian513** [comment]
> 桥接功能相对通用，适合作为独立项目，目前没有内置在bifromq里

请问一下这个桥接模块你们目前没有开源出来吗？
