### ISSUE TITLE
请问下，如果一个topic没有订阅者，往这个上面发送消息还是会被持久化吗?(Qos1-2)

### ISSUE THREAD

**Issue by 12345dotblue** [bifromqio/bifromq#97]
请问下，如果一个topic没有订阅者，往这个上面发送消息还是会被持久化吗?(Qos1-2)

如果是的话， 想请教下怎么避免没有订阅者的topic消息不被持久化（出于性能考虑）。我们的业务场景下会有大量的toipc,  但很多是没有被订阅的。

感谢！

**Comment by popduke** [comment]
往没有订阅的topic上发消息，消息会被丢弃。而且只有CleanSession=false(3.1.1), SessionExpiryInterval > 0 (5.0) 的client订阅topic，消息才会先持久化。

**Comment by popduke** [comment]
Close as inactive
