### ISSUE TITLE
重复登录后通过session接口查不到信息问题

### ISSUE THREAD

**Issue by ijavaofkid** [bifromqio/bifromq#98]
在使用bifroMQ的时候，遇到一个这样的问题，当一个账号登录后，再登录一次，把前面的登录顶掉后，就通过session接口查不到这个登录账号的信息，必须退出后重新登录才能查到。目前定位到这段逻辑导致会话查不到的。
![image](https://github.com/user-attachments/assets/89a82c48-da82-4a35-b9d3-f0339d0fa673)
![image](https://github.com/user-attachments/assets/614e3796-71f2-4481-960f-95f58fc2382b)

**Comment by popduke** [comment]
已在3.3.0中解决
